# NUMPY ARRAY


In [1]:
import numpy as np

### Trial Codes


In [ ]:
arr = np.array([1,2, 3, 4])
print(arr)
li = [1,2,3,4]
print(li)

[1 2 3 4]
[1, 2, 3, 4]


### Creating NUMPY array

In [8]:
import numpy as np
arr = np.array([1,2,3])
print(arr , "and it's dimension =", arr.ndim)

li = []  #Empty list


for i in range(1, 5):
    intInp = int(input("Enter element: "))
    li.append(intInp)  #Input elements

print("List =  ", li, "and type = ", type(li))

npArr = np.array(li)   #converting list into numpy array
print(npArr, " and type =", type(npArr))


print("Dimension = ", npArr.ndim)   #printing it's dimension



[1 2 3] and it's dimension = 1
List =   [8, 3, 66, 4] and type =  <class 'list'>
[ 8  3 66  4]  and type = <class 'numpy.ndarray'>
Dimension =  1


### Dimension of numpy array


In [ ]:
arr = np.array([[[2,3,4,5], [1,2,4,5], [7,39,1,5]]])
print(arr.ndim)
print(arr)

#If we want to create array of 10 dimensions
arr10Dim = np.array([2,3,5,7], ndmin = 10)
print(arr10Dim, "dimension =", arr10Dim.ndim)

3
[[[ 2  3  4  5]
  [ 1  2  4  5]
  [ 7 39  1  5]]]
[[[[[[[[[[2 3 5 7]]]]]]]]]] dimension = 10


### Special numpy arrays

In [ ]:
#arrays with value zeroes
arrOfZeros = np.zeros(5)
print(arrOfZeros, "and dataType of elements:", arrOfZeros.dtype, "and dimension:", arrOfZeros.ndim)

arr3Row4Col = np.zeros((3,4))  #zero array with row = 3 and column = 4
print(arr3Row4Col, "dataType of element:", arr3Row4Col.dtype, "and dimension:", arr3Row4Col.ndim)
print()

#arrays with value 1
arrOfOne = np.ones(5)
print(arrOfOne, "and dataType:", arrOfOne.dtype, "and dimension:", arrOfOne.ndim)
arrOneB = np.ones((4,5))
print(arrOneB)
print()


#Empty array
arr_emp = np.empty(4)
print(arr_emp)  #it will print some garbage values
print()

#range of numbers
arrRange = np.arange(6)
print(arrRange)

reshaped = arrRange.reshape(2,3)
print("Array was reshaped 2X3: \n",reshaped)
print()

#array diagonal elements filled with 1's  (value of diagonal = 1)
arr_diag = np.eye(5)
print(arr_diag, "dimension:", arr_diag.ndim)
print()

#array with values that are spaced linearly in a specified interval
arrLinSpc = np.linspace(0,20, num=6)  #here num is the number of elements which is present inside array
print(arrLinSpc)

[0. 0. 0. 0. 0.] and dataType of elements: float64 and dimension: 1
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] dataType of element: float64 and dimension: 2

[1. 1. 1. 1. 1.] and dataType: float64 and dimension: 1
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[ 5. 10. 15. 20.]

[0 1 2 3 4 5]
Array was reshaped 2X3: 
 [[0 1 2]
 [3 4 5]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] dimension: 2

[ 0.  4.  8. 12. 16. 20.]


### Numpy array with random numbers

In [19]:
# rand() - generate random number between 0 to 1
import numpy as np
var = np.random.rand(5)
print("var =", var,"\n")
var1 = np.random.rand(4,7)   #4 rows and 7 columns
print("var1 =",var1,"\n")
print("Dimension ", var1.ndim, "\n")


#randn() - used to generate a random value close to zero. This may return positive or negative numbers as well
var3 = np.random.randn(6)
print("var3 =", var3,"\n")


# #ranf() -- used to generate numbers between interval[0.0, 1.0] and 1 is not included
var4 = np.random.ranf(5)
print("var4 =", var4,"\n")
randomMAtrix = np.random.ranf(size=(3,4))
print(randomMAtrix,"\n")


#randint() -- used to generate random number between given range
#Syntax randint(minVal, maxVal, totalElement)
var5 = np.random.randint(2,50,9)
print("var5 =", var5,"\n")

var = [0.6147173  0.12165531 0.77496425 0.26924237 0.44237996] 

var1 = [[0.60299806 0.751468   0.60466191 0.40892529 0.04904875 0.35138121
  0.38766443]
 [0.53862694 0.49848687 0.76019432 0.3624028  0.76439064 0.57659408
  0.34303531]
 [0.04244124 0.22869754 0.11798768 0.82707566 0.58609944 0.28828673
  0.33630349]
 [0.23797587 0.95225701 0.36351261 0.16131664 0.5630826  0.01220486
  0.68758802]] 

Dimension  2 

var3 = [ 1.43146303 -0.35449466 -1.40542752 -1.42050897  0.49754446  0.11391981] 

var4 = [9.02010366e-01 5.35807448e-01 8.29327521e-01 6.90793063e-01
 3.18334061e-04] 

[[0.46201554 0.83122589 0.21575855 0.21193026]
 [0.57368085 0.4921631  0.43946449 0.94651091]
 [0.71041717 0.91433176 0.40302112 0.35412474]] 

var5 = [ 7 37 34 29 15 18 40  9 24] 



### DataTypes

In [15]:
var = np.array([1,2,3.3])
print(var, var.dtype)

#characters that are used to represent dataType i-int b-bool u-unsigned f-float o-object s-string
#Conversion from one type to another
x = np.array([3,9,12])
print("DataType:",x.dtype)
newX = np.float64(x)
print("DataType:",newX.dtype,"\n")


x1 = np.array([1,2,3,4], dtype=np.int8)
print(x1.dtype)
x2 = np.array([1,2,3], dtype="f")
print(x2.dtype,"\n")

x3 = np.float64(x)  #data is copied and converted into float
print(x3.dtype)
print(x3)
x = x3.astype(int)
print("Datatype: ",x.dtype)
print()


newArr = np.array([11,2,3,4])
print(newArr.dtype)
newArr = newArr.astype(float)
print(newArr.dtype)

[1.  2.  3.3] float64
DataType: int64
DataType: float64 

int8
float32 

float64
[ 3.  9. 12.]
Datatype:  int64

int64
float64


### Arithematic Operator

In [8]:
#add
add1 = np.array([1,2,3,4])  # we can't write np.array([1,2,3] + 3)
add2 = add1 + 3
print(add1, add2)    #we can write this in this form as well np.add(add1, add2)

add3 = add1 + add2
print(add3)

add4 = np.add(add1, 3)
print(add4)

# operations on 2D array
x1 = np.array([[1,2,3], [4,5,6]])
x2 = np.array([[1,2,3], [1,2,3]])
x1Addx2 = np.add(x1,x2)
print(x1Addx2)
print()

#other operations
diff1 = np.subtract(add2,add1)
print(diff1, " \n")

#like add, subtract we have multiply, divide, power, mod, reciprocol
prod = np.multiply(diff1,3)
print(prod,"\n")

divid = np.divide(diff1,3)
print(divid,"\n")

powerArr = np.power(add1,2)
print(powerArr,"\n")

powerArr = powerArr.astype(float)
reciP = np.reciprocal(powerArr)
print(reciP)


[1 2 3 4] [4 5 6 7]
[ 5  7  9 11]
[4 5 6 7]
[[2 4 6]
 [5 7 9]]

[3 3 3 3]  

[9 9 9 9] 

[1. 1. 1. 1.] 

[ 1  4  9 16] 

[1.         0.25       0.11111111 0.0625    ]


### Arithmetic function

In [18]:
arr= np.array([2,3,1,5,8,4])

print(np.max(arr), "is found at index", np.argmin(arr))
print(np.max(arr)," is found at index", np.argmax(arr))

arr1 = np.array([4,64,169,256,81])
print(np.sqrt(arr1))
#similarly we have functions like sin cos cumsum etc
print("sin value of",arr1, np.sin(arr1))
print("Cos value of",arr1, np.cos(arr1))

#cumsum = sum of previous element
arr2 = np.array([1,2,3,4,5,6])
print(np.cumsum(arr2))

#finding min and max in 2d arrays
#if we want to search row wise then we have to set value of axis = 1
#and if we want to search column wise we have to set value of axis = 0


print()
var1 = np.array([[2,1,3], [9,5,6]])

print(var1, "and dimension:",var1.ndim, "\n")

print(np.max(var1, axis=1), "and index:",np.argmax(var1, axis=1))  #row wise
print(np.min(var1, axis=0), "and index:", np.argmin(var1,axis=0))  #column wise


8 is found at index 2
8  is found at index 4
[ 2.  8. 13. 16.  9.]
sin value of [  4  64 169 256  81] [-0.7568025   0.92002604 -0.60199987 -0.99920803 -0.62988799]
Cos value of [  4  64 169 256  81] [-0.65364362  0.39185723  0.79849619 -0.03979076  0.77668598]
[ 1  3  6 10 15 21]

[[2 1 3]
 [9 5 6]] and dimension: 2 

[3 9] and index: [2 0]
[2 1 3] and index: [0 0 0]


### Shape and ReShape

In [35]:
#array.shape is used to print shape of the array
arr = np.array([[1,2,3], [1,2,3]])
print(arr,"\n",arr.shape)
print(arr.ndim)
print()


arr2 = np.array([[1],[2],[3]])
print(arr2,"\n", arr2.shape)
print()

var1 = np.array([1,2,3,4], ndmin=4)
print(var1,"\n", var1.shape,"\n")

#reshape(2,3) 2 - row and 3 column
arr3 = np.array([1,2,3,4,5,6])
print(arr3)
print(arr3.reshape(3,2))
print()

arr4 = np.arange(1,13)  #or np.linespace(1,12,12,dtype=int) 
print(arr4,"\n")
print(arr4.reshape(2,3,2))

[[1 2 3]
 [1 2 3]] 
 (2, 3)
2

[[1]
 [2]
 [3]] 
 (3, 1)

[[[[1 2 3 4]]]] 
 (1, 1, 1, 4) 

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
